name = "HEMI"
authors = ["Juan Carlos Castañeda", "Rodrigo Chang", "Oscar Solís", "Mauricio Vargas"]

[deps]
CPIDataBase = "e4c88d09-b53c-432a-84e8-7deb46235234"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
julia = "1.5.3"
