name = "CPIDataBase"
uuid = "e4c88d09-b53c-432a-84e8-7deb46235234"
authors = ["Rodrigo Chang <rrcp777@gmail.com> and contributors"]
version = "0.1.0"

[deps]
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
